// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"nunu-project/internal/migration"
	"nunu-project/internal/repository"
	"nunu-project/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*migration.Migrate, func(), error) {
	db := repository.NewDB(viperViper)
	migrate := migration.NewMigrate(db, logger)
	return migrate, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewUserRepository)

var MigrateSet = wire.NewSet(migration.NewMigrate)
