// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"nunu-project/internal/handler"
	"nunu-project/internal/middleware"
	"nunu-project/internal/repository"
	"nunu-project/internal/server"
	"nunu-project/internal/service"
	"nunu-project/pkg/helper/sid"
	"nunu-project/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	jwt := middleware.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	serviceService := service.NewService(logger, sidSid, jwt)
	db := repository.NewDB(viperViper)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	orderRepository := repository.NewOrderRepository(repositoryRepository)
	orderService := service.NewOrderService(serviceService, orderRepository)
	orderHandler := handler.NewOrderHandler(handlerHandler, orderService)
	blogRepository := repository.NewBlogRepository(repositoryRepository)
	blogService := service.NewBlogService(serviceService, blogRepository)
	blogHandler := handler.NewBlogHandler(handlerHandler, blogService)
	engine := server.NewServerHTTP(logger, jwt, userHandler, orderHandler, blogHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var SidSet = wire.NewSet(sid.NewSid)

var JwtSet = wire.NewSet(middleware.NewJwt)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewOrderHandler, handler.NewBlogHandler)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewOrderService, service.NewBlogService)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewUserRepository, repository.NewOrderRepository, repository.NewBlogRepository)
